In this section, We wanna learn and test the Scipy package in the python
as you know the Scipy package in Python is very important, Also it looks like the NumPy package
this pack is about Scientific calculations, Algebraic equations, Image Processing, Optimization...

Import:

In [1]:
import numpy as np
import pandas as pd
import scipy as sc
from scipy import special,optimize

In [2]:
import scipy.constants 
res = scipy.constants.physical_constants['alpha particle mass']
print(res)  

(6.6446573357e-27, 'kg', 2e-36)


K-means Algorithm:

In [3]:
from scipy.cluster.vq import vq,kmeans,whiten
from numpy import vstack,array
from numpy.random import rand
#data generation with three features 
data = vstack((rand(100,3)+array([.5,.5,.5]),rand(100,3)))
data = whiten(data)
#We can create the three ways
centrodis,_ = kmeans(data,3)
print(centrodis)
clx,_ = vq(data,centrodis)
print(clx)

[[0.94745987 2.03276404 1.33975121]
 [1.77691475 0.78474326 1.60023014]
 [2.71546218 2.62928628 2.78333   ]]
[2 2 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 0 2 2 1 2 2 2 2 1 2 1 0 0 0 1 0 0 1 0 0 0
 1 1 2 1 1 0 1 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 2 1 1 1 0 0 0 1 1 0 0 0
 0 1 1 1 0 0 0 1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1
 2 0 1 1 0 0 1 1 0 0 0 1 2 0 1]


Fourier transform:

In [4]:
import numpy as np 
# import matplotlib.pyplot as plt
from scipy.fftpack import fft
#create an array with random n numbers
x = np.array([1.0,2.0,1.0,-1.0,1.5])
y = fft(x)
# plt.scatter(y,x)
print(y)

[ 4.5       -0.j          2.08155948-1.65109876j -1.83155948+1.60822041j
 -1.83155948-1.60822041j  2.08155948+1.65109876j]


Scipy in the python it was made by Blas and Atlaslapack and Abilities in the Linear Algebra

In [5]:
from scipy import linalg
import numpy as np 
a = np.array([[1,3,5],[2,5,1],[2,3,8]])
b = np.array([10,8,3])
x = linalg.solve(a,b)
print(x)

[-9.28  5.16  0.76]


Determinal:

In [6]:
from scipy import linalg
import numpy as np
a = np.array([[1,2],[3,4]])
x = linalg.det(a)
print(x)

-2.0


In [7]:
# from scipy import linalg 
# import numpy as np
# a = np.array([[2,8,6],[4,1,3]])
# #Passing the values to the eig function
# l,v = linalg.eig(a)
# #printing the result for eigen values
# print(l)
# #printing the result for eigen vectors
# print(v)a

Singular Value Decomposition: "SVD"

In [8]:
from scipy import linalg
import numpy as np 
a = np.random.rand(3,2)+1.j*np.random.rand(3,2)
#passing the valuses to the wig funcation
U,s,Vh = linalg.svd(a)
print(U,s,Vh )

[[-0.3839893 -0.46341569j -0.03382614-0.41335576j -0.47226536-0.49270311j]
 [-0.48216486-0.16560352j -0.02112978-0.48177852j  0.62925747+0.33402179j]
 [-0.5805914 -0.20200067j  0.253726  +0.72873789j  0.12452297-0.10567682j]] [1.88055421 0.66596586] [[-0.77370277+0.j         -0.54996932-0.31451195j]
 [ 0.63354875+0.j         -0.67163385-0.38408847j]]


Image Processing:

In [9]:
# from PIL import Image
# #load the image
# image = Image.open('ship.png')